export enum Types {
  SET_USER = "SET_USER",
  GET_ACCOUNT = "GET_ACCOUNT",
  GET_TRANS = "GET_TRANS",
  GET_OBJECTS = "GET_OBJECTS",
  GET_BUDGET = "GET_BUDGET",
  SET_BUDGET = "SET_BUDGET",
  SET_AUTH = "SET_AUTH",
}
